env: hok

test_greedy: True
test_nepisode: 64 # 32
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 50000

obs_last_action: True

env_args:
  map_name: hok